<?
// Use logging if you want to log the cURL requests
define(LOGGING,     false);
// We <3 JSON
define(USE_JSON,    true);

// Enter any excluded terms here
$excludedTerms  = array(
    "2011", "with", "review", "video", "apps", "preview", "interview", "this", "online", "working", "play", "cross", "social", "says", "xvid", "hdtv", "gamezebo", "many", "using", "here", "gets", "last", "could", "color", "best",
    "city", "design", "gameplay", "first", "trailer", "internet", "live", "gaming", "network", "gamer", "week", "shared", "real", "into", "edition", "coming", "over", "can't", "sell", "deal", "black", "over",
    "march", "dead", "about", "only", "more", "games", "what", "photo", "want", "support", "should", "than", "show", "data", "know", "will",
    "arcane", "functional", "single", "free", "from", "world", "your", "game", "that", "better", "things", "still", "history");
?>